identifier: l8d6v4f61e47m3f5
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: D:\Projets\Angular projects\my-blog
distFolder: dist/my-blog
outDir: D:\Projets\Angular projects\my-blog\dist\static
handle404: ''
allowErrorCollect: true
